version: "3.9"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=example
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - "./data:/data/db"
    environment:
      POSTGRES_PASSWORD: example
